import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Group90091(),
        ]),
      ),
    );
  }
}

class Group90091 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 151,
          height: 193,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/151x193"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 112,
          height: 141,
          decoration: BoxDecoration(
            image: DecorationImage(
              image: NetworkImage("https://via.placeholder.com/112x141"),
              fit: BoxFit.fill,
            ),
          ),
        ),
        Container(
          width: 428,
          height: 520,
          decoration: ShapeDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.56, -0.83),
              end: Alignment(-0.56, 0.83),
              colors: [Colors.white.withOpacity(0.20000000298023224), Color(0x3307DD92)],
            ),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(20),
                topRight: Radius.circular(20),
              ),
            ),
          ),
        ),
        Text(
          'Approved!',
          style: TextStyle(
            color: Colors.black,
            fontSize: 24,
            fontFamily: 'Inter',
            fontWeight: FontWeight.w500,
            height: 0,
          ),
        ),
        Text(
          'You are now part of zevo',
          style: TextStyle(
            color: Colors.black,
            fontSize: 16,
            fontFamily: 'Inter',
            fontWeight: FontWeight.w400,
            height: 0,
          ),
        ),
        Container(
          width: 428,
          height: 520,
          decoration: ShapeDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.56, -0.83),
              end: Alignment(-0.56, 0.83),
              colors: [Colors.white.withOpacity(0.20000000298023224), Color(0x3306B9F0)],
            ),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(20),
                topRight: Radius.circular(20),
              ),
            ),
          ),
        ),
        Text(
          'You are Present',
          style: TextStyle(
            color: Colors.black,
            fontSize: 24,
            fontFamily: 'Inter',
            fontWeight: FontWeight.w500,
            height: 0,
          ),
        ),
      ],
    );
  }
}